### ISSUE TITLE
Exceptions in link definition are silently caught and ignored 

### ISSUE THREAD

**Issue by DeffiDeffi** [gdebrauwer/laravel-hateoas#35]
Right now, exceptions thrown in link methods of hateoas classes are silently caught here:
https://github.com/gdebrauwer/laravel-hateoas/blob/100e0590d54860e057a16ef767105081223bd46e/src/HateoasManager.php#L45

Is there a reason for this behaviour, and would it be possible to add an option to not catch exceptions? I keep running into this wondering why the link collection of a resource is empty -- especially because I disabled lazy loading of relationships in Laravel, so exceptions are thrown whenever I use an unloaded relationship in a link. 

It's difficult to debug this on entities with a lot of links. Currently my go-to way of debugging is commenting out one link after another until I've found the one that has an exception.

Thank you for this great package by the way, I've been using it a lot and it's working great.

**Comment by gdebrauwer** [comment]
I added that try-catch so an API call would not fail completely if there's just a small error in a hateoas class.

We could remove that try-catch, but that would require a new major version I think 🤔

**Comment by DeffiDeffi** [comment]
I understand. I'd much rather the entire request failed because it's easier to identify the errors that way. E.g. I recently changed the authorization implementation on one of my projects and did not notice the hateoas failing until users complained they were able to see resources, but could not edit or save them. Of course I could test for the existence of the relations returned but I do think it's a bit unintuitive.

As a compromise, would you accept a pull request that adds a [configuration file](https://laravel.com/docs/9.x/packages#configuration)? That way we could add the option to disable the try-catch but keep it enabled by default to prevent a breaking change in existing projects.

**Comment by gdebrauwer** [comment]
I released v2 of this package with only PHP 8+ and Laravel 9 support, and I also made the change that exceptions are not handled anymore 🙂
